path: /mnt/D/Projects/anpr/model/datasets #dataset root folder
train: /mnt/D/Projects/anpr/model/datasets/train/images #train folder
val: /mnt/D/Projects/anpr/model/datasets/valid/images #val folder
test: /mnt/D/Projects/anpr/model/datasets/test/images #test folder

#Classes

names: ["License_Plate"]
