import {
	LuCommand,
	LuAlertTriangle,
	LuArrowRight,
	LuCheck,
	LuChevronLeft,
	LuChevronRight,
	LuCircuitBoard,
	LuCreditCard,
	LuFile,
	LuFileText,
	LuHelpCircle,
	LuImage,
	LuLaptop,
	LuLayoutDashboard,
	LuListTodo,
	LuLoader2,
	LuLogIn,
	LuMoon,
	LuMoreVertical,
	LuPizza,
	LuPlus,
	LuSettings,
	LuSunMedium,
	LuTrash,
	LuTwitter,
	LuUser,
	LuUser2,
	LuUserX2,
	LuX,
	LuPackage,
} from "react-icons/lu";
import { MdOutlineRestaurantMenu } from "react-icons/md";
import { IoFastFood } from "react-icons/io5";

export const Icons = {
	dashboard: LuLayoutDashboard,
	logo: LuCommand,
	login: LuLogIn,
	close: LuX,
	profile: LuUser2,
	spinner: LuLoader2,
	kanban: LuCircuitBoard,
	chevronLeft: LuChevronLeft,
	chevronRight: LuChevronRight,
	trash: LuTrash,
	employee: LuUserX2,
	post: LuFileText,
	page: LuFile,
	media: LuImage,
	settings: LuSettings,
	billing: LuCreditCard,
	ellipsis: LuMoreVertical,
	add: LuPlus,
	warning: LuAlertTriangle,
	user: LuUser,
	arrowRight: LuArrowRight,
	help: LuHelpCircle,
	pizza: LuPizza,
	sun: LuSunMedium,
	moon: LuMoon,
	laptop: LuLaptop,
	twitter: LuTwitter,
	check: LuCheck,
	logs: LuListTodo,
	menu: MdOutlineRestaurantMenu,
	item: IoFastFood,
	order: LuPackage,
};

export type Icon = keyof typeof Icons;
